In [15]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])


array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [7]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [8]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [9]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [10]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [12]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [13]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [14]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [ ]:
tf.random_normal([3]).eval()

In [ ]:
tf.random_uniform([2]).eval()

In [ ]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

In [ ]:
tf.reduce_mean(x, axis=0).eval()

In [ ]:
tf.reduce_mean(x, axis=1).eval()

In [ ]:
tf.reduce_mean(x, axis=-1).eval()

In [ ]:
tf.reduce_sum(x).eval()

In [ ]:
tf.reduce_sum(x, axis=0).eval()

In [ ]:
tf.reduce_sum(x, axis=-1).eval()

In [ ]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

In [ ]:
tf.argmax(x, axis=1).eval()

In [ ]:
tf.argmax(x, axis=-1).eval()

In [ ]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

In [ ]:
tf.reshape(t, shape=[-1, 3]).eval()

In [ ]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

In [ ]:
tf.squeeze([[0], [1], [2]]).eval()

In [ ]:
tf.expand_dims([0, 1, 2], 1).eval()

In [ ]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

In [ ]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

In [ ]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

In [ ]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

In [ ]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

In [ ]:
tf.stack([x, y, z], axis=1).eval()

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

In [ ]:
tf.zeros_like(x).eval()

In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

In [ ]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

In [ ]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

In [ ]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

In [ ]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

In [ ]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))